[package]
name = "simple-tor-tc"
version = "0.1.0"
authors = ["tcharding <tobin@coblox.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
