[package]
name = "simple-tor-tc"
version = "0.1.0"
authors = ["Tobin C. Harding <tobin@coblox.tech>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
tokio = { version = "0.2", features = ["rt-threaded", "time", "macros", "sync", "tcp"] }
torut = "0.1"
tor-stream = "0.2"
